create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table public.participants (
  id uuid primary key default gen_random_uuid(),
  towel_number text not null unique check (length(btrim(towel_number)) between 1 and 40),
  name text not null check (length(btrim(name)) between 1 and 120),
  status text not null default 'eligible' check (status in ('eligible', 'won', 'absent', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.gifts (
  id uuid primary key default gen_random_uuid(),
  gift_number text not null unique check (length(btrim(gift_number)) between 1 and 40),
  status text not null default 'available' check (status in ('available', 'claimed', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.draw_results (
  id uuid primary key default gen_random_uuid(),
  sequence_number bigint generated by default as identity unique,
  participant_id uuid not null references public.participants(id) on delete restrict,
  gift_id uuid unique references public.gifts(id) on delete restrict,
  status text not null default 'participant_selected' check (status in ('participant_selected', 'winner_confirmed', 'completed', 'cancelled')),
  drawn_by uuid not null references auth.users(id),
  participant_drawn_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint completed_has_gift check (status <> 'completed' or (gift_id is not null and completed_at is not null)),
  constraint pending_has_no_gift check (status = 'completed' or gift_id is null)
);

create unique index draw_results_one_committed_participant
  on public.draw_results(participant_id)
  where status <> 'cancelled';
create unique index draw_results_one_active_per_host
  on public.draw_results(drawn_by)
  where status in ('participant_selected', 'winner_confirmed');
create index participants_status_idx on public.participants(status);
create index gifts_status_idx on public.gifts(status);
create index draw_results_status_idx on public.draw_results(status);
create index draw_results_created_at_idx on public.draw_results(created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger participants_updated_at before update on public.participants
for each row execute function public.set_updated_at();
create trigger gifts_updated_at before update on public.gifts
for each row execute function public.set_updated_at();

alter table public.participants enable row level security;
alter table public.gifts enable row level security;
alter table public.draw_results enable row level security;

create policy "authenticated hosts read participants" on public.participants
  for select to authenticated using (true);
create policy "authenticated hosts insert participants" on public.participants
  for insert to authenticated with check (true);
create policy "authenticated hosts update participants" on public.participants
  for update to authenticated using (true) with check (true);
create policy "authenticated hosts delete participants" on public.participants
  for delete to authenticated using (true);

create policy "authenticated hosts read gifts" on public.gifts
  for select to authenticated using (true);
create policy "authenticated hosts insert gifts" on public.gifts
  for insert to authenticated with check (true);
create policy "authenticated hosts update gifts" on public.gifts
  for update to authenticated using (true) with check (true);
create policy "authenticated hosts delete gifts" on public.gifts
  for delete to authenticated using (true);

create policy "authenticated hosts read draw results" on public.draw_results
  for select to authenticated using (true);

revoke all on public.draw_results from anon, authenticated;
grant select on public.draw_results to authenticated;
grant usage, select on sequence public.draw_results_sequence_number_seq to authenticated;

create or replace function public.require_authenticated()
returns uuid language plpgsql stable set search_path = '' as $$
declare user_id uuid := auth.uid();
begin
  if user_id is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  return user_id;
end;
$$;

create or replace function public.draw_random_participant()
returns table(draw_result_id uuid, participant_id uuid, towel_number text, participant_name text, draw_status text)
language plpgsql security definer set search_path = '' as $$
declare chosen public.participants; new_draw public.draw_results; user_id uuid;
begin
  user_id := public.require_authenticated();

  if not exists (select 1 from public.gifts where status = 'available') then
    raise exception 'Tiada hadiah yang tersedia';
  end if;

  if exists (select 1 from public.draw_results where drawn_by = user_id and status in ('participant_selected', 'winner_confirmed')) then
    raise exception 'Selesaikan cabutan semasa dahulu';
  end if;

  select p.* into chosen
  from public.participants p
  where p.status = 'eligible'
    and not exists (select 1 from public.draw_results d where d.participant_id = p.id and d.status <> 'cancelled')
  order by extensions.gen_random_bytes(16)
  for update of p skip locked
  limit 1;

  if chosen.id is null then raise exception 'Tiada peserta yang layak'; end if;

  insert into public.draw_results(participant_id, drawn_by)
  values (chosen.id, user_id) returning * into new_draw;

  return query select new_draw.id, chosen.id, chosen.towel_number, chosen.name, new_draw.status;
end;
$$;

create or replace function public.confirm_participant_winner(p_draw_result_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare selected_draw public.draw_results; user_id uuid;
begin
  user_id := public.require_authenticated();
  select * into selected_draw from public.draw_results where id = p_draw_result_id and drawn_by = user_id for update;
  if selected_draw.id is null then raise exception 'Cabutan tidak ditemui'; end if;
  if selected_draw.status <> 'participant_selected' then raise exception 'Status cabutan tidak sah'; end if;
  update public.participants set status = 'won' where id = selected_draw.participant_id and status = 'eligible';
  if not found then raise exception 'Peserta tidak lagi layak'; end if;
  update public.draw_results set status = 'winner_confirmed' where id = selected_draw.id;
end;
$$;

create or replace function public.mark_selected_participant_absent(p_draw_result_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare selected_draw public.draw_results; participant_status text; user_id uuid;
begin
  user_id := public.require_authenticated();
  select * into selected_draw from public.draw_results where id = p_draw_result_id and drawn_by = user_id for update;
  if selected_draw.id is null then raise exception 'Cabutan tidak ditemui'; end if;
  if selected_draw.status <> 'participant_selected' then raise exception 'Status cabutan tidak sah'; end if;
  select status into participant_status from public.participants where id = selected_draw.participant_id for update;
  if participant_status = 'eligible' then
    update public.participants set status = 'absent' where id = selected_draw.participant_id;
  elsif participant_status not in ('absent', 'disabled') then
    raise exception 'Peserta tidak boleh dibatalkan';
  end if;
  update public.draw_results set status = 'cancelled' where id = selected_draw.id;
end;
$$;

create or replace function public.draw_random_gift(p_draw_result_id uuid)
returns table(draw_result_id uuid, gift_id uuid, gift_number text, draw_status text, completed_at timestamptz)
language plpgsql security definer set search_path = '' as $$
declare selected_draw public.draw_results; chosen public.gifts; done_at timestamptz := now(); user_id uuid;
begin
  user_id := public.require_authenticated();
  select * into selected_draw from public.draw_results where id = p_draw_result_id and drawn_by = user_id for update;
  if selected_draw.id is null then raise exception 'Cabutan tidak ditemui'; end if;
  if selected_draw.status = 'completed' then
    return query select selected_draw.id, selected_draw.gift_id, g.gift_number, selected_draw.status, selected_draw.completed_at
      from public.gifts g where g.id = selected_draw.gift_id;
    return;
  end if;
  if selected_draw.status <> 'winner_confirmed' then raise exception 'Pemenang belum disahkan'; end if;

  select g.* into chosen from public.gifts g
  where g.status = 'available'
  order by extensions.gen_random_bytes(16)
  for update of g skip locked limit 1;
  if chosen.id is null then raise exception 'Tiada hadiah yang tersedia'; end if;

  update public.gifts set status = 'claimed' where id = chosen.id and status = 'available';
  if not found then raise exception 'Hadiah tidak lagi tersedia'; end if;
  update public.draw_results set gift_id = chosen.id, status = 'completed', completed_at = done_at where id = selected_draw.id;

  return query select selected_draw.id, chosen.id, chosen.gift_number, 'completed'::text, done_at;
end;
$$;

create or replace function public.reset_draw_data(p_confirmation text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.require_authenticated();
  if p_confirmation <> 'SET SEMULA CABUTAN' then raise exception 'Frasa pengesahan tidak tepat'; end if;
  delete from public.draw_results where id is not null;
  perform setval('public.draw_results_sequence_number_seq', 1, false);
  update public.participants set status = 'eligible' where status in ('won', 'absent');
  update public.gifts set status = 'available' where status = 'claimed';
end;
$$;

create or replace function public.clear_participants(p_confirmation text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.require_authenticated();
  if p_confirmation <> 'PADAM SEMUA PESERTA' then raise exception 'Frasa pengesahan tidak tepat'; end if;
  delete from public.draw_results where id is not null;
  perform setval('public.draw_results_sequence_number_seq', 1, false);
  delete from public.participants where id is not null;
  update public.gifts set status = 'available' where status = 'claimed';
end;
$$;

create or replace function public.clear_gifts(p_confirmation text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.require_authenticated();
  if p_confirmation <> 'PADAM SEMUA HADIAH' then raise exception 'Frasa pengesahan tidak tepat'; end if;
  delete from public.draw_results where id is not null;
  perform setval('public.draw_results_sequence_number_seq', 1, false);
  delete from public.gifts where id is not null;
  update public.participants set status = 'eligible' where status = 'won';
end;
$$;

revoke all on function public.require_authenticated() from public, anon;
revoke all on function public.draw_random_participant() from public, anon;
revoke all on function public.confirm_participant_winner(uuid) from public, anon;
revoke all on function public.mark_selected_participant_absent(uuid) from public, anon;
revoke all on function public.draw_random_gift(uuid) from public, anon;
revoke all on function public.reset_draw_data(text) from public, anon;
revoke all on function public.clear_participants(text) from public, anon;
revoke all on function public.clear_gifts(text) from public, anon;
grant execute on function public.draw_random_participant() to authenticated;
grant execute on function public.confirm_participant_winner(uuid) to authenticated;
grant execute on function public.mark_selected_participant_absent(uuid) to authenticated;
grant execute on function public.draw_random_gift(uuid) to authenticated;
grant execute on function public.reset_draw_data(text) to authenticated;
grant execute on function public.clear_participants(text) to authenticated;
grant execute on function public.clear_gifts(text) to authenticated;
